# Generated by Django 6.0.4 on 2026-04-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_skillcategory_experience_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
