# Generated by Django 6.0.4 on 2026-04-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='role_titles',
            field=models.CharField(default='Full Stack Developer, Python Expert', help_text='Comma-separated titles for typewriter effect', max_length=512),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
